version: "3.1"

services:
  ####################### PPR Database Definition #######################
  bcsc_db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1qazxSw2
      - POSTGRES_DB=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    # volumes:
    #   - dbdata:/var/lib/postgresql/data
# volumes:
#   dbdata: