version: "3.1"

services:
  ####################### PPR Database Definition #######################
  bcsc_db:
    image: postgres:11
    restart: always
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: 5432
      DATABASE_TEST_HOST: ${DATABASE_TEST_HOST}
      DATABASE_TEST_NAME: ${DATABASE_TEST_NAME}
      DATABASE_TEST_PORT: 5432
      DATABASE_TEST_USER: ${DATABASE_TEST_USER}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DATABASE_ADMIN_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_TEST_PASSWORD: ${DATABASE_TEST_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5
  #################### Jaeger Tracing Service Definition ####################
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      
volumes:
  dbdata: