---
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: egress-internet
spec:
  description: |
    allow the devops-platform-security-demo namespace to talk to the internet.
  source:
    - - $namespace=oultzp-dev
  destination:
    - - ext:network=any
---
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: intra-namespace-comms
spec:
  description: |
    allow the devops-platform-security-demo namespace to talk to itself
  source:
    - - $namespace=oultzp-dev
  destination:
    - - $namespace=oultzp-dev
---
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: int-cluster-k8s-api-comms
spec:
  description: |
    allow devops-platform-security-demo pods to talk to the k8s api
  destination:
  - - int:network=internal-cluster-api-endpoint
  source:
  - - $namespace=oultzp-tools
  - - $namespace=oultzp-dev
  - - $namespace=oultzp-test