---
kind: Template
apiVersion: v1
metadata:
  name: "${API_NAME}-configmap-template"
  creationTimestamp: 
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${API_NAME}-${TAG_NAME}-secret"
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
  stringData:
    DYNAMIC_TEST_API_TOKEN: "${DYNAMIC_TEST_API_TOKEN}"
    DYNAMIC_PROD_API_TOKEN: "${DYNAMIC_PROD_API_TOKEN}"
  type: Opaque
parameters:
- name: API_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: selfservice-api
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: BC-ServiceCard
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: NAMESPACE
  displayName: Name
  description: This is a namespace in which instance is deployed
  required: true
  value: oultzp
- name: DYNAMIC_TEST_API_TOKEN
  displayName: Dynamic API Test Token
  description: Dynamic API Test Token
  required: true
  value: ""
- name: DYNAMIC_PROD_API_TOKEN
  displayName: Dynamic API Prod Token
  description: Dynamic API Prod Token
  required: true
  value: ""