---
kind: Template
apiVersion: v1
metadata:
  name: "${WEB_NAME}-pipeline"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${WEB_NAME}-${TAG_NAME}-pipeline"
    creationTimestamp: 
    labels:
      app: "${WEB_NAME}-${TAG_NAME}"
      app-group: "${APP_GROUP}"
      template: "${WEB_NAME}-pipeline"
  spec:
    triggers:
    - type: GitHub
      github:
        secretReference:
          name: "${WEBHOOK}"
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
      sourceSecret:
        name: github-credentials
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: "${JENKINS_FILE}"
    output: {}
    resources: {}
    postCommit: {}
    nodeSelector: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
parameters:
- name: WEB_NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: selfservice-ui
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: BC-ServiceCard
- name: TAG_NAME
  displayName: Pipeline purpose
  description: The activity that this pipeline will manage. eg. build, test, promote,
    etc.
  required: true
  value: dev
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/BCSC-SS.git
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: dev
- name: WEBHOOK
  displayName: Secret name for the webhook.
  description: The name of the Secret that holds the webhook.
  required: true
  value: bcsc-ss
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: 
- name: SOURCE_CONTEXT_DIR_API
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: /selfservice-api
- name: SOURCE_CONTEXT_DIR_DB
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: /selfservice-db
- name: JENKINS_FILE
  displayName: The Jenksinfile this pipeline should use.
  description: The Jenkinsfile this pipeline should use.
  required: false
  value: "jenkins/jenkinsfile.dev.groovy"