---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Deployment template for a BC Service Card SelfService frontend application
    tags: ui, BC-serviceCard
  name: "${WEB_NAME}"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: 
    labels:
      app: "${WEB_NAME}"
      app-group: "${APP_GROUP}"
    name: "${WEB_NAME}"
  spec:
    replicas: 1
    selector:
      app: "${WEB_NAME}"
      deploymentconfig: "${WEB_NAME}"
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: 
        labels:
          app: "${WEB_NAME}"
          deploymentconfig: "${WEB_NAME}"
      spec:
        containers:
        - image: "${WEB_NAME}"
          imagePullPolicy: Always
          name: "${WEB_NAME}"
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: API_SERVICE_NAME
            value: "${API_SERVICE_NAME}"
          - name: API_PATH
            value: "${API_PATH}"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: "/"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${WEB_NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${WEB_NAME}:${TAG_NAME}"
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 
    labels:
      app: "${WEB_NAME}"
    name: "${WEB_NAME}"
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: "${WEB_NAME}"
      deploymentconfig: "${WEB_NAME}"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: "${WEB_NAME}"
    name: "${WEB_NAME}"
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${WEB_NAME}"
      weight: 100
parameters:
- description: The name assigned to all of the openshift objects defined in this template.
    It is also the name of runtime image you want.
  displayName: Name
  name: WEB_NAME
  required: true
  value: selfservice-ui
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: BC-ServiceCard
- description: The namespace where to get the above image name
  displayName: Image Namespace
  name: IMAGE_NAMESPACE
  required: true
  value: oultzp-tools
- description: The name of the service endpoint for the API.  Used to wire up to an
    API endpoint within the same project; overriding the URL defined by API_URL.
  displayName: API Service Name
  name: API_SERVICE_NAME
  required: false
  value: selfservice-api
- description: The root path for the API.  Used in conjunction with API_SERVICE_NAME.
  displayName: API Path
  name: API_PATH
  required: true
  value: "/selfservice-api"
- description: The TAG name for this environment, e.g., dev, test, prod
  displayName: Env TAG name
  name: TAG_NAME
  value: dev
- description: Frontend Storage Capacity
  displayName: Storage Capacity
  name: VOLUME_CAPACITY
  value: 1Gi
