---
kind: Template
apiVersion: v1
metadata:
  name: "${WEB_NAME}-secretmap-template"
  creationTimestamp: 
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${WEB_NAME}-dev-secret"
    labels:
      app: "${WEB_NAME}"
      template: "${WEB_NAME}-deploy"
  data:
    KEYCLOAK_CLIENT_SECRET: "${KEYCLOAKCLIENTSECRET_DEV}"
    JWT_OIDC_CLIENT_SECRET: "${KEYCLOAKCLIENTSECRET_DEV}"
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${WEB_NAME}-test-secret"
    labels:
      app: "${WEB_NAME}"
      template: "${WEB_NAME}-deploy"
  data:
    KEYCLOAK_CLIENT_SECRET: "${KEYCLOAKCLIENTSECRET_TEST}"
    JWT_OIDC_CLIENT_SECRET: "${KEYCLOAKCLIENTSECRET_TEST}"
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${WEB_NAME}-prod-secret"
    labels:
      app: "${WEB_NAME}"
      template: "${WEB_NAME}-deploy"
  data:
    KEYCLOAK_CLIENT_SECRET: "${KEYCLOAKCLIENTSECRET_PROD}"
    JWT_OIDC_CLIENT_SECRET: "${KEYCLOAKCLIENTSECRET_PROD}"
parameters:
- name: WEB_NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: selfservice-ui
- name: KEYCLOAKCLIENTSECRET_DEV
  displayName: keycloak Client Secret - Dev
  description: keycloak Client Secret - Dev
  required: true
  value: 'VGhpcyBpcyB0ZW1wIHZhbHVlCg=='
- name: KEYCLOAKCLIENTSECRET_TEST
  displayName: keycloak Client Secret - Test
  description: keycloak Client Secret - Test
  required: true
  value: 'VGhpcyBpcyB0ZW1wIHZhbHVlCg=='
- name: KEYCLOAKCLIENTSECRET_PROD
  displayName: keycloak Client Secret - Prod
  description: keycloak Client Secret - Prod
  required: true
  value: 'VGhpcyBpcyB0ZW1wIHZhbHVlCg=='