---
kind: Template
apiVersion: v1
metadata:
  name: "${WEB_NAME}-build-template"
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${WEB_NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${WEB_NAME}-build"
    labels:
      app: "${WEB_NAME}-build"
  spec:
    triggers:
    - type: ImageChange
    - type: ConfigChange
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
      sourceSecret:
        name: github-credentials
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: "${DOCKER_FILE_PATH}"
        buildArgs:
        - name: "API_BASE_URL"
          value: "http://${API_NAME}-${TAG_NAME}.pathfinder.gov.bc.ca/"
        - name: KEYCLOAK_URL
          value: ${KEYCLOAKURL}
        - name: KEYCLOAK_REALM
          value: ${KEYCLOAKREALM}
        - name: KEYCLOAK_CLIENT
          value: ${KEYCLOAKCLIENT}
        - name: KEYCLOAK_CLIENT_SECRET
          value: ${KEYCLOAKCLIENTSECRET}
    output:
      to:
        kind: ImageStreamTag
        name: "${WEB_NAME}:${OUTPUT_IMAGE_TAG}"
parameters:
- name: WEB_NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: selfservice-ui
- name: API_NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: selfservice-api
- name: TAG_NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: dev
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/BCSC-SS.git
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: master
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: "/selfservice-ui"
- name: SOURCE_IMAGE_KIND
  displayName: Source Image Kind
  description: The 'kind' (type) of the  source image; typically ImageStreamTag, or
    DockerImage.
  required: true
  value: ImageStreamTag
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the source image.
  required: true
  value: selfservice-ui
- name: SOURCE_IMAGE_TAG
  displayName: Source Image Tag
  description: The tag of the source image.
  required: true
  value: dev
- name: DOCKER_FILE_PATH
  displayName: Docker File Path
  description: The path to the docker file defining the build.
  required: false
  value: "./Dockerfile"
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: The tag given to the built image.
  required: true
  value: dev
- name: KEYCLOAKURL
  displayName: keycloak Url
  description: keycloak Url.
  required: true
  value: 'http://keycloak.aottech.com:8080/auth'
- name: KEYCLOAKREALM
  displayName: keycloak Url
  description: keycloak Url.
  required: true
  value: 'bcselfservice'
- name: KEYCLOAKCLIENT
  displayName: keycloak Url
  description: keycloak Url.
  required: true
  value: 'client_bcselfservice'
- name: KEYCLOAKCLIENTSECRET
  displayName: keycloak Url
  description: keycloak Url.
  required: true
  value: '5a0c2bed-88d0-4320-b6f2-aba399a5d235'